Fix correct param passing from Airflow (version >2.3.3) to HOP
damavis/airflow-hop-plugin pull request #38
Opened 2024-05-29 14:51 UTC by vegaskyo

**Description**
**Issue**
There was an issue with passing parameters and macro variables from Apache Airflow to Apache HOP. The parameters were not being correctly interpreted in the HOP logs, showing the raw macro variable names (e.g., {{ ds }}) instead of their expected values (e.g., 20-05-2024).

**Solution**
Changed the parameter name from param to **hop_param**. This adjustment ensures compatibility and correct macro convertion in HOP logs.

**Additional Information**
In Apache Airflow 2.3.3, the params variable is utilized during DAG serialization. Using params as a variable name in third-party operators can lead to issues. For more information, refer to the [Apache Airflow Pull Request #20640](https://github.com/apache/airflow/pull/20640/files/03550d26654f77bbcd91b44a1372320cb48bda6e)

2024-05-29 15:02 UTC, PereAL7 requested changes
You should correct `template_fields` on both operators so the airflow templates render correctly into their respective values.

**Additional info:**
https://airflow.apache.org/docs/apache-airflow/stable/howto/custom-operator.html#templating

2024-05-29 15:18 UTC, vegaskyo commented
> You should correct `template_fields` on both operators so the airflow templates render correctly into their respective values.
> 
> **Additional info:** https://airflow.apache.org/docs/apache-airflow/stable/howto/custom-operator.html#templating

I tested the code without changing **template_fields**, and all tests passed with both macros and normal string params. Therefore, I believe we do not need to modify template_fields.

2024-05-30 07:41 UTC, PereAL7 approved these changes

2024-05-30 07:41 UTC, PereAL7 commented
You are right. I didn't notice that you only changed the constructor parameter and that is not affected by template_fields. Thanks for your contribution!

2024-05-30 07:41 UTC, merged